name: internally
recipe: drupal9
config:
  webroot: .
services:
  database:
    type: mysql
    portforward: true
    creds:
      user: internally
      password: internally
      database: internally